from __future__ import annotations

import math

NATIVE_NUM_BEAMS = 1081
LIDAR_DIM = NATIVE_NUM_BEAMS
LIDAR_FOV_DEG = 270.0
LIDAR_ANGLE_MIN = math.radians(-0.5 * LIDAR_FOV_DEG)
LIDAR_ANGLE_INCREMENT = math.radians(LIDAR_FOV_DEG / (LIDAR_DIM - 1))
LIDAR_RANGE_MIN = 0.06
LIDAR_RANGE_MAX = 30.0

IMU_DIM = 6
PROPRIO_DIM = 16
ACTOR_OBS_DIM = 1097
NUM_ACTIONS = 2
CRITIC_OBS_DIM = 392

LIDAR_START = 0
IMU_START = LIDAR_DIM
VESC_SPEED = IMU_START + IMU_DIM
VESC_CURRENT = VESC_SPEED + 1
THROTTLE_CURRENT = VESC_CURRENT + 1
THROTTLE_PRED = THROTTLE_CURRENT + 1
STEER_T = THROTTLE_PRED + 1
STEER_T1 = STEER_T + 1
STEER_T2 = STEER_T1 + 1
STEER_DELTA0 = STEER_T2 + 1
STEER_DELTA1 = STEER_DELTA0 + 1
STEER_DELTA2 = STEER_DELTA1 + 1

assert ACTOR_OBS_DIM == STEER_DELTA2 + 1
assert PROPRIO_DIM == ACTOR_OBS_DIM - LIDAR_DIM

GRAVITY_MS2 = 9.81

ACTOR_LAYOUT_VERSION = 2
SENSOR_POLICY_FORMAT_VERSION = 4
OBS_PREPROCESSING_VERSION = 3
ARTIFACT_SCOPE_SIM_TRAINING = "simulation_training_only"
CONTROL_HZ = 10.0
ACTOR_ARCHITECTURE_NAME = "lidar_cnn_gru"
STEERING_ACTION_MODE = "delta"
STEERING_DELTA_MAX_RAD = math.pi / 60.0
MAX_STEER_RAD = 0.33
CLIP_ACTIONS = 1.0
ACT_LIMIT = 1.0
OBS_NORM_CLIP = 10.0
OBS_NORM_EPS = 1e-8
GRU_HIDDEN_DIM = 512
CNN_PROJECTION_DIM = 256
ALLOWED_LIDAR_POOL_BINS = frozenset((16, 32, 64))
