"""Local sensor layout constants (mirrored; no f1tenth_policy import)."""

from __future__ import annotations

import math

NATIVE_NUM_BEAMS = 1081
LIDAR_DIM = NATIVE_NUM_BEAMS
LIDAR_FOV_DEG = 270.0
LIDAR_ANGLE_MIN = math.radians(-0.5 * LIDAR_FOV_DEG)
LIDAR_ANGLE_INCREMENT = math.radians(LIDAR_FOV_DEG / (LIDAR_DIM - 1))
LIDAR_RANGE_MIN = 0.06
LIDAR_RANGE_MAX = 30.0
LIDAR_RELIABLE_RANGE = 12.0

IMU_DIM = 6
PROPRIO_DIM = 16
SENSOR_OBS_DIM = LIDAR_DIM + PROPRIO_DIM

IMU_START = LIDAR_DIM
VESC_SPEED = IMU_START + IMU_DIM
VESC_CURRENT = VESC_SPEED + 1
THROTTLE_CURRENT = VESC_CURRENT + 1
THROTTLE_PRED = THROTTLE_CURRENT + 1
STEER_T = THROTTLE_PRED + 1
STEER_T1 = STEER_T + 1
STEER_T2 = STEER_T1 + 1
STEER_DELTA0 = STEER_T2 + 1
STEER_DELTA1 = STEER_DELTA0 + 1
STEER_DELTA2 = STEER_DELTA1 + 1

VESC_CURRENT_SCALE_A = 5.0
MAX_STEER_RAD = 0.33
STEERING_DELTA_MAX_RAD = math.pi / 60.0
GRAVITY = 9.81

assert SENSOR_OBS_DIM == STEER_DELTA2 + 1
