"""Default training configuration — sole Lee / ADR-0011 sensor path."""

DEFAULT_CONFIG = {
    "config_version": 4,
    "policy_format_version": 4,
    "simulator": {
        "id": "f1tenth-torch",
        "version": 1,
    },
    "obs": {
        "num_obs": 392,
        "num_actor_obs": 1097,
        "actor_layout_version": 2,
        "obs_scales": {
            "lin_vel": 1.0,
            "ang_vel": 1.0,
            "lin_acc": 1.0,
        },
        "clip_obs": 50.0,
        "norm_clip": 10.0,
        "norm_eps": 1e-8,
        "contact_margin_m": 0.08,
        "enable_opponent_obs": True,
        "opponent_obs_dim": 8,
        "opp_obs_ahead_m": 40.0,
        "opp_obs_behind_m": 20.0,
        "future_track_num_points": 60,
        "future_track_horizon_s": 6.0,
        "future_track_min_lookahead_m": 5.0,
    },
    "env": {
        "num_actions": 2,
        "episode_length": 120.0,
        "expected_lap_speed_mps": 3.5,
        "episode_lap_multiplier": 3.0,
        "control_interval": 20,
        "sim_dt": 0.005,
        "clip_actions": 1.0,
        "steering_action_mode": "delta",
        "steering_delta_max_rad": 0.05235987755982988,
        "simulate_action_latency": True,
        "term_speed_threshold": 0.2,
        "term_not_moving_time_s": 2.0,
        "term_not_moving_min_ds": 1e-3,
        "term_heading_error_rad": 3.0,
        "car_spawn_pos": (0.0, 0.0, 0.01),
        "car_spawn_rot": (0.0, 0.0, 0.0),
        "reset_speed_min_mps": 1.0,
        "reset_speed_max_mps": 7.0,
        "reset_stationary_probability": 0.10,
        "stationary_startup_grace_s": 1.5,
        "reset_spawn_margin_m": 0.2,
        "reset_spawn_yaw_jitter_rad": 0.1,
        "opponent_spawn_lateral_independent": True,
        "max_speed": 15.0,
        "delta_max": 0.33,
        "wheelbase": 0.325,
        "track_width": 0.253,
        "wheel_radius": 0.053,
        "f_drive_max": 23.0,
        "f_brake_max": 5.2,
        "power_max": 320.0,
        "k_drive_front": 0.5,
        "t_delta": 0.1,
        "c_roll": 0.0,
        "dragcoeff": 0.075,
        "tire_friction": 0.65,
        "v_eps": 0.1,
        "enable_aero_drag": True,
        "drive_torque_sign": 1.0,
        "slip_min_lat": 0.2,
        "slip_min_active_long": 0.1,
        "slip_min_passive_long": 0.4,
        "warp_sim": {
            "roll_stiffness_front": 0.47,
            "longitudinal_slew_rate_per_s": 4.444444444444445,
            "tire_relax_len": 0.0,
        },
        "longitudinal_mode": "force",
        "track": "IV_2026_SIM",
        "opponent_strategy": None,
        "opponent_mix": {
            "scripted_weight": 0.5,
            "policy_weight": 0.5,
            "policy_speed_cap_prob": 0.5,
            "policy_speed_cap_range": [5.0, 7.0],
        },
        "opponent_target_speed": 2.5,
        "opponent_target_speed_range": [2.0, 4.0],
        "opponent_lateral_offset_m": 0.5,
        "opponent_spawn_gap_min_m": 3.0,
        "opponent_spawn_gap_max_m": 80.0,
        "opponent_spawn_behind_prob": 0.3,
        "opponent_reset_speed_min_mps": 1.0,
        "opponent_reset_speed_max_mps": 4.0,
        "opponent_kp_ey": 1.0,
        "opponent_kh_heading": 1.0,
        "opponent_kp_speed": 1.0,
        "term_on_collision": True,
        "collision_term_speed_mps": 4.0,
        "boundary_mode": "first_contact_terminal",
        "car_length": 0.568,
        "car_width": 0.296,
        "collision_margin_m": 0.0,
        "domain_randomization": {
            "enabled": True,
            "tire_friction_range": [0.60, 0.70],
            "vehicle_mass_range": [3.6, 3.9],
            "action_latency_steps_range": [0, 1],
            "obs_latency_steps_range": [0, 1],
            "obs_noise_std_range": [0.0, 0.01],
            "action_latency_steps_max": 3,
            "drive_scale_range": [0.7777777777777778, 1.4444444444444444],
            "steer_bias_range": [0.0, 0.0],
            "lidar_range_noise_std_range": [0.0, 0.0],
            "lidar_far_dropout_prob_range": [0.0, 0.0],
            "lidar_dropout_prob_range": [0.0, 0.0],
            "lidar_angle_bias_range": [0.0, 0.0],
            "lidar_extrinsic_xy_range": [-0.01, 0.01],
            "lidar_extrinsic_yaw_range": [-0.008726646, 0.008726646],
            "imu_accel_bias_range": [-0.08, 0.08],
            "imu_gyro_bias_range": [-0.005, 0.005],
            "imu_accel_noise_std_range": [0.005, 0.015],
            "imu_gyro_noise_std_range": [0.0005, 0.0015],
            "imu_axis_misalign_range": [0.0, 0.0],
            "vesc_speed_bias_range": [0.0, 0.0],
            "vesc_current_bias_range": [-0.005, 0.005],
            "vesc_speed_noise_std_range": [0.0, 0.0],
            "vesc_current_noise_std_range": [0.0, 0.005],
        },
    },
    "sensor": {
        "num_beams": 1081,
        "fov_deg": 270.0,
        "range_min_m": 0.06,
        "range_max_m": 30.0,
        "reliable_range_m": 10.0,
        "beam_decimation": 1,
        "vesc_current_scale_a": 5.0,
        "max_march_steps": 512,
        "lidar_offset_x": 0.27,
        "lidar_offset_y": 0.0,
        "lidar_offset_yaw": 0.0,
    },
    "reward": {
        "progress_max_lateral_m": 1.0,
        "wall_contact_coefficient": 20.0,
        "wall_cost_mode": "one_shot",
        "passing_gate_ahead_m": 40.0,
        "passing_gate_behind_m": 20.0,
        "global_reward_scale": 1.0,
        "steering_history_c_s": 182.883569,
        "steering_history_c_o": 0.034,
        "steering_history_c_d": 0.014,
        "rear_end_gate": "any_contact",
        "reward_scales": {
            "progress": 1.0,
            "passing": 3.0,
            "collision": 6.0,
            "rear_end": 0.5,
            "steering_change": 0.5,
            "steering_history": 0.5,
        },
    },
    "model": {
        "actor_type": "lidar_cnn_gru",
        "actor_hidden_layers": [1024, 1024, 1024],
        "critic_hidden_layers": [1024, 1024, 1024],
        "lidar_pool_bins": 32,
        "num_quantiles": 32,
        "rew_gamma": 0.9896,
        "n_step": 7,
        "alpha": 0.01,
        "actor_lr": 2.5e-5,
        "critic_lr": 2.5e-5,
        "replay_buffer_limit": 3_000_000,
        "replay_full_reinit": True,
        "lidar_aug_enabled": True,
        "lidar_aug_max_shift_beams": 4,
        "batch_size": 1024,
        "minimum_train_transitions": 200_000,
        "sampled_replay_rows_per_transition": 2.0,
    },
    "schedule": {
        "total_transitions": 500_000_000,
        "log_interval_transitions": 51_200,
        "export_interval_transitions": 5_120_000,
        "eval_interval_transitions": 0,
    },
    # Seeded fixed champion pool. One entry is selected once at startup.
    "fixed_opponents": {
        "entries": [],
    },
}
