// Parity tests for rl_obs_core against fixtures generated by the Python pipeline.
//
// obs_fixture.txt is produced by gen_obs_fixture.py from the deployed Python
// ObservationBuilder, which the f1tenth_rl_agent parity test pins to the training
// f1tenth_env observation math. Passing here means the C++ observation equals the
// one the policy trained on (within float tolerance).
#include <array>
#include <cmath>
#include <cctype>
#include <fstream>
#include <memory>
#include <string>
#include <vector>

#include "gtest/gtest.h"

#include "f1tenth_rl_vehicle/rl_obs_core.hpp"

using f1tenth_rl_vehicle::DetectionResult;
using f1tenth_rl_vehicle::DetectorConfig;
using f1tenth_rl_vehicle::ObsConfig;
using f1tenth_rl_vehicle::OpponentDetector;
using f1tenth_rl_vehicle::OpponentState;
using f1tenth_rl_vehicle::ScanPoint;
using f1tenth_rl_vehicle::SlipEstimatorConfig;
using f1tenth_rl_vehicle::SlipEstimatorInput;
using f1tenth_rl_vehicle::SlipEstimatorState;
using f1tenth_rl_vehicle::TrackData;
using f1tenth_rl_vehicle::TrackObservationBuilder;
using f1tenth_rl_vehicle::VehicleState;
using f1tenth_rl_vehicle::loadTrackCsv;

namespace
{
std::string fixturePath()
{
  // Set by CMake (ament_add_gtest gets the source dir via a compile definition).
#ifdef OBS_FIXTURE_PATH
  return OBS_FIXTURE_PATH;
#else
  return "obs_fixture.txt";
#endif
}
}  // namespace

TEST(RlObsCore, MatchesPythonFixture)
{
  std::ifstream f(fixturePath());
  ASSERT_TRUE(f.is_open()) << "cannot open fixture: " << fixturePath();

  int n = 0;
  f >> n;
  ASSERT_GT(n, 1);
  std::vector<double> xs(n), ys(n), wl(n), wr(n);
  for (int i = 0; i < n; ++i) {
    f >> xs[i] >> ys[i] >> wl[i] >> wr[i];
  }

  ObsConfig cfg;
  double samples, horizon, width, contact, clip, sv, sa, sc;
  f >> samples >> horizon >> width >> contact >> clip >> sv >> sa >> sc;
  cfg.num_obs = 390;
  cfg.future_track_num_points = static_cast<int>(samples);
  cfg.future_track_horizon_s = horizon;
  cfg.future_track_width = width;
  cfg.contact_margin_m = contact;
  cfg.clip_obs = clip;
  cfg.lin_vel_scale = sv;
  cfg.ang_vel_scale = sa;
  cfg.lin_acc_scale = sc;

  TrackObservationBuilder builder(xs, ys, wl, wr, cfg);

  int num_cases = 0;
  f >> num_cases;
  ASSERT_GT(num_cases, 0);

  double max_diff = 0.0;
  for (int c = 0; c < num_cases; ++c) {
    VehicleState st;
    f >> st.pos_x >> st.pos_y >> st.yaw >> st.vx >> st.vy >> st.wz >> st.ax >> st.ay >>
    st.last_throttle >> st.last_steer;
    for (int i = 0; i < 8; ++i) {
      f >> st.tyre_slip[i];
    }
    std::vector<double> expected(cfg.num_obs);
    for (int i = 0; i < cfg.num_obs; ++i) {
      f >> expected[i];
    }

    std::vector<float> obs = builder.build(st);
    ASSERT_EQ(static_cast<int>(obs.size()), cfg.num_obs);
    for (int i = 0; i < cfg.num_obs; ++i) {
      double d = std::abs(static_cast<double>(obs[i]) - expected[i]);
      max_diff = std::max(max_diff, d);
      EXPECT_LT(d, 1e-4) << "case " << c << " index " << i
                         << " got " << obs[i] << " expected " << expected[i];
    }
  }
  EXPECT_LT(max_diff, 1e-4) << "max obs parity diff = " << max_diff;

  // Opponent section.
  int num_opp_cases = 0;
  if (f >> num_opp_cases) {
    ObsConfig ocfg = cfg;
    ocfg.enable_opponent_obs = true;
    TrackObservationBuilder opp_builder(xs, ys, wl, wr, ocfg);

    double opp_max_diff = 0.0;
    for (int c = 0; c < num_opp_cases; ++c) {
      VehicleState st;
      f >> st.pos_x >> st.pos_y >> st.yaw >> st.vx >> st.vy >> st.wz >> st.ax >>
      st.ay >> st.last_throttle >> st.last_steer;
      for (int i = 0; i < 8; ++i) {
        f >> st.tyre_slip[i];
      }
      OpponentState opp;
      f >> opp.pos_x >> opp.pos_y >> opp.vx >> opp.vy;
      opp.present = true;

      std::vector<double> expected(ocfg.num_obs);
      for (int i = 0; i < ocfg.num_obs; ++i) {
        f >> expected[i];
      }

      std::vector<float> obs = opp_builder.build(st, opp);
      ASSERT_EQ(static_cast<int>(obs.size()), ocfg.num_obs);
      for (int i = 0; i < ocfg.num_obs; ++i) {
        double d = std::abs(static_cast<double>(obs[i]) - expected[i]);
        opp_max_diff = std::max(opp_max_diff, d);
        EXPECT_LT(d, 1e-4) << "opp case " << c << " index " << i
                           << " got " << obs[i] << " expected " << expected[i];
      }
    }
    EXPECT_LT(opp_max_diff, 1e-4) << "max opponent obs parity diff = " << opp_max_diff;
  }
}

TEST(RlObsCore, TyreSlipMatchesFormula)
{
  // Straight-rolling wheel: spin_rate * radius == v_fwd -> zero slip ratio,
  // zero lateral velocity -> zero slip angle.
  const std::array<bool, 4> active{true, true, true, true};
  const double min_lat = 0.2, min_active = 0.1, min_passive = 0.4;
  std::array<double, 4> v_fwd{2.0, 2.0, 2.0, 2.0};
  std::array<double, 4> v_lat{0.0, 0.0, 0.0, 0.0};
  const double wheel_radius = 0.053;
  const double rolling_spin = 2.0 / wheel_radius;
  std::array<double, 4> spin{rolling_spin, rolling_spin, rolling_spin, rolling_spin};
  auto slip = f1tenth_rl_vehicle::computeTyreSlip(
    v_fwd, v_lat, spin, wheel_radius, active, min_lat, min_active, min_passive);
  for (int i = 0; i < 8; ++i) {
    EXPECT_NEAR(slip[i], 0.0, 1e-9);
  }

  // Locked wheel (spin 0) while moving forward, drive active ->
  // slip_ratio = (0 - v_fwd) / (|v_fwd| + min_active_long).
  std::array<double, 4> spin0{0.0, 0.0, 0.0, 0.0};
  auto slip2 = f1tenth_rl_vehicle::computeTyreSlip(
    v_fwd, v_lat, spin0, wheel_radius, active, min_lat, min_active, min_passive);
  const double expected = -2.0 / (2.0 + min_active);
  for (int i = 0; i < 4; ++i) {
    EXPECT_NEAR(slip2[i], expected, 1e-9);
  }
}

TEST(RlObsCore, QuasiStaticLoadTransfer)
{
  // At rest: every wheel carries its static share (ratio 1.0). Order [LR,RR,LF,RF].
  auto rest = f1tenth_rl_vehicle::computeQuasiStaticLoad(0.0, 0.0);
  for (int i = 0; i < 4; ++i) {
    EXPECT_NEAR(rest[i], 1.0, 1e-9);
  }

  // +ax (forward accel) loads the rear axle, unloads the front; left/right balanced.
  auto fwd = f1tenth_rl_vehicle::computeQuasiStaticLoad(4.0, 0.0);
  EXPECT_GT(fwd[0], 1.0);
  EXPECT_GT(fwd[1], 1.0);
  EXPECT_LT(fwd[2], 1.0);
  EXPECT_LT(fwd[3], 1.0);
  EXPECT_NEAR(fwd[0], fwd[1], 1e-9);
  EXPECT_NEAR(fwd[2], fwd[3], 1e-9);

  // +ay (left turn) loads the right (outer) wheels; each axle mean stays static.
  auto left = f1tenth_rl_vehicle::computeQuasiStaticLoad(0.0, 4.0);
  EXPECT_GT(left[1], left[0]);
  EXPECT_GT(left[3], left[2]);
  EXPECT_NEAR(0.5 * (left[0] + left[1]), 1.0, 1e-9);
  EXPECT_NEAR(0.5 * (left[2] + left[3]), 1.0, 1e-9);

  // Extreme accel never yields a negative normal-load ratio.
  auto extreme = f1tenth_rl_vehicle::computeQuasiStaticLoad(-50.0, 50.0);
  for (int i = 0; i < 4; ++i) {
    EXPECT_GE(extreme[i], 0.0);
  }
}

TEST(RlObsCore, EstimateSlipBlockLowSpeedFallback)
{
  SlipEstimatorConfig cfg;
  cfg.slip_speed_min_mps = 0.3;
  cfg.slip_obs_mean = {0.1, 0.2, 0.97, 0.98, -0.01, -0.02, -0.03, -0.04};
  SlipEstimatorState state;
  SlipEstimatorInput in;
  in.vesc_vx = 0.1;
  in.dt = 0.1;
  in.have_pf_vel = true;
  in.pf_vx_body = 0.1;
  in.pf_vy_body = 0.0;

  auto slip = f1tenth_rl_vehicle::estimateSlipBlock(state, cfg, in);
  for (int i = 0; i < 8; ++i) {
    EXPECT_NEAR(slip[i], cfg.slip_obs_mean[i], 1e-9);
  }
}

TEST(RlObsCore, EstimateSlipBlockCruiseNearZeroRearSlip)
{
  SlipEstimatorConfig cfg;
  cfg.wheel_radius_m = 0.053;
  cfg.slip_speed_min_mps = 0.3;
  cfg.vx_ground_lp_alpha = 0.0;
  cfg.vy_filter_tau_s = 0.5;
  SlipEstimatorState state;
  SlipEstimatorInput in;
  in.vesc_vx = 3.0;
  in.dt = 0.1;
  in.have_pf_vel = true;
  in.pf_vx_body = 3.0;
  in.pf_vy_body = 0.0;
  in.last_throttle = 0.5;

  auto slip = f1tenth_rl_vehicle::estimateSlipBlock(state, cfg, in);
  EXPECT_NEAR(slip[0], 0.0, 0.05);
  EXPECT_NEAR(slip[1], 0.0, 0.05);
  for (int i = 0; i < 8; ++i) {
    EXPECT_TRUE(std::isfinite(slip[i]));
  }
}

namespace
{
// A clean closed circle track (radius R) so Frenet projection is unambiguous,
// unlike an open straight polyline whose auto-closing segment is degenerate.
struct CircleTrack
{
  std::vector<double> xs, ys, wl, wr;
};

CircleTrack makeCircle(double radius, int num, double half_width)
{
  CircleTrack t;
  for (int i = 0; i < num; ++i) {
    const double th = 2.0 * M_PI * static_cast<double>(i) / num;
    t.xs.push_back(radius * std::cos(th));
    t.ys.push_back(radius * std::sin(th));
    t.wl.push_back(half_width);
    t.wr.push_back(half_width);
  }
  return t;
}

// A small cluster of beams (in beam order, map frame) around (cx, cy), spread
// tangentially (+y) so it stays on the centerline of a circle centred at origin.
std::vector<ScanPoint> blobBeams(double cx, double cy, int count, double spacing)
{
  std::vector<ScanPoint> beams;
  const double y0 = cy - 0.5 * (count - 1) * spacing;
  for (int i = 0; i < count; ++i) {
    ScanPoint p;
    p.x = cx;
    p.y = y0 + i * spacing;
    p.valid = true;
    beams.push_back(p);
  }
  return beams;
}

// Car-sized blob with free-space flanks for the foreground gate.
std::vector<ScanPoint> carBlobScan(double cx, double cy, int count, double spacing)
{
  std::vector<ScanPoint> scan;
  scan.push_back(ScanPoint{0.0, 0.0, false});
  const auto blob = blobBeams(cx, cy, count, spacing);
  scan.insert(scan.end(), blob.begin(), blob.end());
  scan.push_back(ScanPoint{0.0, 0.0, false});
  return scan;
}

std::string gymScanFixturePath()
{
#ifdef GYM_SCAN_FIXTURE_PATH
  return GYM_SCAN_FIXTURE_PATH;
#else
  return "gym_scan_fixture.json";
#endif
}

// Minimal JSON helpers for the gym scan fixture schema:
// { "frames": [ { "ranges": [...], "angle_min", "angle_increment",
//               "ego_x", "ego_y", "ego_yaw", "opp_x", "opp_y" }, ... ] }
void skipWs(const std::string & s, size_t & i)
{
  while (i < s.size() && (s[i] == ' ' || s[i] == '\n' || s[i] == '\r' || s[i] == '\t')) {
    ++i;
  }
}

bool expectChar(const std::string & s, size_t & i, char c)
{
  skipWs(s, i);
  if (i >= s.size() || s[i] != c) {
    return false;
  }
  ++i;
  return true;
}

bool parseNumber(const std::string & s, size_t & i, double & out)
{
  skipWs(s, i);
  const size_t start = i;
  while (i < s.size() &&
    (std::isdigit(static_cast<unsigned char>(s[i])) || s[i] == '-' || s[i] == '+' ||
    s[i] == '.' || s[i] == 'e' || s[i] == 'E'))
  {
    ++i;
  }
  if (i == start) {
    return false;
  }
  try {
    out = std::stod(s.substr(start, i - start));
    return true;
  } catch (...) {
    return false;
  }
}

bool parseDoubleArray(const std::string & s, size_t & i, std::vector<double> & out)
{
  if (!expectChar(s, i, '[')) {
    return false;
  }
  out.clear();
  skipWs(s, i);
  if (i < s.size() && s[i] == ']') {
    ++i;
    return true;
  }
  while (i < s.size()) {
    double v = 0.0;
    if (!parseNumber(s, i, v)) {
      return false;
    }
    out.push_back(v);
    skipWs(s, i);
    if (i < s.size() && s[i] == ',') {
      ++i;
      continue;
    }
    break;
  }
  return expectChar(s, i, ']');
}

struct GymScanFrame
{
  std::vector<double> ranges;
  double angle_min = 0.0;
  double angle_increment = 0.0;
  double ego_x = 0.0;
  double ego_y = 0.0;
  double ego_yaw = 0.0;
  double opp_x = 0.0;
  double opp_y = 0.0;
};

bool parseGymScanFrame(const std::string & s, size_t & i, GymScanFrame & frame)
{
  if (!expectChar(s, i, '{')) {
    return false;
  }
  frame = GymScanFrame{};
  while (i < s.size()) {
    skipWs(s, i);
    if (i < s.size() && s[i] == '}') {
      ++i;
      return true;
    }
    if (i >= s.size() || s[i] != '"') {
      return false;
    }
    const size_t key_start = ++i;
    while (i < s.size() && s[i] != '"') {
      ++i;
    }
    const std::string key = s.substr(key_start, i - key_start);
    ++i;
    if (!expectChar(s, i, ':')) {
      return false;
    }
    if (key == "ranges") {
      if (!parseDoubleArray(s, i, frame.ranges)) {
        return false;
      }
    } else {
      double v = 0.0;
      if (!parseNumber(s, i, v)) {
        return false;
      }
      if (key == "angle_min") frame.angle_min = v;
      else if (key == "angle_increment") frame.angle_increment = v;
      else if (key == "ego_x") frame.ego_x = v;
      else if (key == "ego_y") frame.ego_y = v;
      else if (key == "ego_yaw") frame.ego_yaw = v;
      else if (key == "opp_x") frame.opp_x = v;
      else if (key == "opp_y") frame.opp_y = v;
    }
    skipWs(s, i);
    if (i < s.size() && s[i] == ',') {
      ++i;
    }
  }
  return false;
}

bool loadGymScanFixture(
  const std::string & path, std::vector<GymScanFrame> & frames,
  std::string * track_csv_out = nullptr)
{
  std::ifstream f(path);
  if (!f.is_open()) {
    return false;
  }
  std::string json((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
  size_t i = 0;
  if (!expectChar(json, i, '{')) {
    return false;
  }
  frames.clear();
  while (i < json.size()) {
    skipWs(json, i);
    if (i < json.size() && json[i] == '}') {
      return true;
    }
    if (i >= json.size() || json[i] != '"') {
      return false;
    }
    const size_t key_start = ++i;
    while (i < json.size() && json[i] != '"') {
      ++i;
    }
    const std::string key = json.substr(key_start, i - key_start);
    ++i;
    if (!expectChar(json, i, ':')) {
      return false;
    }
    if (key == "frames") {
      if (!expectChar(json, i, '[')) {
        return false;
      }
      skipWs(json, i);
      if (i < json.size() && json[i] == ']') {
        ++i;
      } else {
        while (i < json.size()) {
          GymScanFrame frame;
          if (!parseGymScanFrame(json, i, frame)) {
            return false;
          }
          frames.push_back(frame);
          skipWs(json, i);
          if (i < json.size() && json[i] == ',') {
            ++i;
            continue;
          }
          break;
        }
      }
      if (!expectChar(json, i, ']')) {
        return false;
      }
    } else if (key == "track_csv" && track_csv_out != nullptr) {
      skipWs(json, i);
      if (i >= json.size() || json[i] != '"') {
        return false;
      }
      const size_t val_start = ++i;
      while (i < json.size() && json[i] != '"') {
        ++i;
      }
      *track_csv_out = json.substr(val_start, i - val_start);
      ++i;
    } else {
      // Skip unknown top-level values (e.g. metadata strings).
      skipWs(json, i);
      if (i < json.size() && json[i] == '"') {
        ++i;
        while (i < json.size() && json[i] != '"') {
          ++i;
        }
        ++i;
      } else if (i < json.size() && json[i] == '[') {
        ++i;
        int depth = 1;
        while (i < json.size() && depth > 0) {
          if (json[i] == '[') {
            ++depth;
          } else if (json[i] == ']') {
            --depth;
          }
          ++i;
        }
      } else {
        double dummy = 0.0;
        if (!parseNumber(json, i, dummy)) {
          return false;
        }
      }
    }
    skipWs(json, i);
    if (i < json.size() && json[i] == ',') {
      ++i;
    }
  }
  return false;
}

// Mirror opponent_detector_node.cpp onScan (lidar offset zero).
std::vector<ScanPoint> rangesToMapBeams(
  const std::vector<double> & ranges, double angle_min, double angle_increment,
  double ego_x, double ego_y, double ego_yaw,
  double range_min = 0.0, double range_max = 30.0)
{
  const double c_ego = std::cos(ego_yaw);
  const double s_ego = std::sin(ego_yaw);
  std::vector<ScanPoint> beams(ranges.size());
  for (size_t j = 0; j < ranges.size(); ++j) {
    const double r = ranges[j];
    ScanPoint pt;
    const bool valid = std::isfinite(r) && r >= range_min && r <= range_max;
    if (valid) {
      const double ang = angle_min + static_cast<double>(j) * angle_increment;
      const double lx = r * std::cos(ang);
      const double ly = r * std::sin(ang);
      pt.x = ego_x + c_ego * lx - s_ego * ly;
      pt.y = ego_y + s_ego * lx + c_ego * ly;
      pt.valid = true;
    }
    beams[j] = pt;
  }
  return beams;
}
}  // namespace

TEST(OpponentObs, PureBlockBuildsFromState)
{
  const CircleTrack t = makeCircle(20.0, 120, 1.5);
  ObsConfig cfg;
  cfg.enable_opponent_obs = true;
  cfg.num_obs = 390;
  TrackObservationBuilder builder(t.xs, t.ys, t.wl, t.wr, cfg);

  VehicleState st;
  st.pos_x = 20.0;
  st.pos_y = 0.0;
  st.yaw = M_PI / 2.0;  // tangent at theta=0 points +y
  st.vx = 3.0;

  OpponentState opp;
  opp.present = true;
  const double th = 0.15;
  opp.pos_x = 20.0 * std::cos(th);
  opp.pos_y = 20.0 * std::sin(th);
  std::vector<float> obs = builder.build(st, opp);
  ASSERT_EQ(static_cast<int>(obs.size()), 390);
  EXPECT_GT(obs[384], 0.0f);                  // rel_x: opponent ahead in ego frame
  EXPECT_GT(obs[388], 0.0f);                  // gap_norm: opponent ahead along track
}

TEST(OpponentObs, ZeroMaskForcesSentinel)
{
  const CircleTrack t = makeCircle(20.0, 120, 1.5);
  ObsConfig cfg;
  cfg.enable_opponent_obs = true;
  cfg.zero_opponent_obs = true;
  cfg.num_obs = 390;
  TrackObservationBuilder builder(t.xs, t.ys, t.wl, t.wr, cfg);

  VehicleState st;
  st.pos_x = 20.0;
  st.pos_y = 0.0;
  st.yaw = M_PI / 2.0;
  st.vx = 3.0;

  OpponentState opp;
  opp.present = true;
  const double th = 0.15;
  opp.pos_x = 20.0 * std::cos(th);
  opp.pos_y = 20.0 * std::sin(th);
  opp.vx = 1.0;
  opp.vy = 0.5;

  std::vector<float> obs = builder.build(st, opp);
  ASSERT_EQ(static_cast<int>(obs.size()), 390);
  for (int i = 384; i < 390; ++i) {
    EXPECT_FLOAT_EQ(obs[i], 0.0f) << "masked block index " << i;
  }
}

TEST(OpponentDetectorTest, Clustering)
{
  const CircleTrack t = makeCircle(20.0, 120, 1.5);
  ObsConfig cfg;
  TrackObservationBuilder builder(t.xs, t.ys, t.wl, t.wr, cfg);
  DetectorConfig dcfg;
  OpponentDetector det(builder, dcfg);

  std::vector<ScanPoint> beams;
  // Group A: 4 points spaced 0.05.
  for (int i = 0; i < 4; ++i) {
    beams.push_back(ScanPoint{0.0, i * 0.05, true});
  }
  beams.push_back(ScanPoint{0.0, 0.0, false});  // invalid break
  // Group B: 3 points, far from group A (> cluster_gap).
  for (int i = 0; i < 3; ++i) {
    beams.push_back(ScanPoint{5.0, i * 0.05, true});
  }

  auto clusters = det.cluster(beams);
  ASSERT_EQ(clusters.size(), 2u);
  EXPECT_EQ(clusters[0].count, 4);
  EXPECT_EQ(clusters[1].count, 3);
}

TEST(OpponentDetectorTest, CorridorGateRejectsWall)
{
  const CircleTrack t = makeCircle(20.0, 120, 1.5);
  ObsConfig cfg;
  TrackObservationBuilder builder(t.xs, t.ys, t.wl, t.wr, cfg);
  DetectorConfig dcfg;
  OpponentDetector det(builder, dcfg);

  // On-centerline cluster (radius 20) is in the corridor.
  auto on = det.cluster(blobBeams(20.0, 0.0, 5, 0.05));
  ASSERT_EQ(on.size(), 1u);
  EXPECT_TRUE(det.inCorridor(on[0]));

  // Near-boundary cluster (radius ~21.4 -> |ey| ~1.4 > 1.5 - 0.2) is rejected.
  auto wall = det.cluster(blobBeams(21.4, 0.0, 5, 0.05));
  ASSERT_EQ(wall.size(), 1u);
  EXPECT_FALSE(det.inCorridor(wall[0]));
}

TEST(OpponentDetectorTest, ForegroundGateRejectsContiguousWall)
{
  const CircleTrack t = makeCircle(20.0, 120, 1.5);
  ObsConfig cfg;
  TrackObservationBuilder builder(t.xs, t.ys, t.wl, t.wr, cfg);
  DetectorConfig dcfg;
  dcfg.foreground_jump_m = 0.30;
  dcfg.max_range_m = 0.0;  // isolate the foreground logic from the range gate
  OpponentDetector det(builder, dcfg);

  // A car blob 4 m ahead of an ego at the origin, flanked by empty (free-space)
  // beams -> both flanks are background, so it stands out.
  std::vector<ScanPoint> car;
  car.push_back(ScanPoint{0.0, 0.0, false});
  for (int i = 0; i < 5; ++i) {
    car.push_back(ScanPoint{4.0, -0.1 + 0.05 * i, true});
  }
  car.push_back(ScanPoint{0.0, 0.0, false});
  auto cc = det.cluster(car);
  ASSERT_EQ(cc.size(), 1u);
  EXPECT_TRUE(det.standsOut(car, cc[0], 0.0, 0.0));

  // The same blob but flanked by returns at the *same* range (a contiguous wall
  // surface that merely fragmented into car-sized pieces). The flanks are split
  // from the body by a just-larger-than-cluster_gap gap, so it is its own cluster
  // but does not stand out from its neighbours -> rejected.
  std::vector<ScanPoint> wallframe;
  wallframe.push_back(ScanPoint{4.0, -0.6, true});  // left flank (gap 0.45 > 0.30)
  for (int i = 0; i < 5; ++i) {
    wallframe.push_back(ScanPoint{4.0, -0.1 + 0.05 * i, true});
  }
  wallframe.push_back(ScanPoint{4.0, 0.6, true});   // right flank
  auto wf = det.cluster(wallframe);
  ASSERT_EQ(wf.size(), 3u);                          // body sits in the middle
  EXPECT_FALSE(det.standsOut(wallframe, wf[1], 0.0, 0.0));
}

TEST(OpponentDetectorTest, StationaryOpponentConfirms)
{
  const CircleTrack t = makeCircle(20.0, 120, 1.5);
  ObsConfig cfg;
  TrackObservationBuilder builder(t.xs, t.ys, t.wl, t.wr, cfg);
  DetectorConfig dcfg;  // min_track_age_frames = 3, min_speed_mps = 0
  dcfg.max_range_m = 0.0;  // synthetic blob sits 20 m out (radius-20 circle)
  OpponentDetector det(builder, dcfg);

  DetectionResult res;
  for (int k = 0; k < 3; ++k) {
    res = det.update(blobBeams(20.0, 0.0, 5, 0.05), 0.0, 0.0, 0.1 * k);
  }
  EXPECT_TRUE(res.present);             // confirmed despite zero motion
  EXPECT_NEAR(res.vx, 0.0, 1e-6);
  EXPECT_NEAR(res.vy, 0.0, 1e-6);
  EXPECT_NEAR(res.pos_x, 20.0, 1e-6);
  EXPECT_NEAR(res.pos_y, 0.0, 1e-6);
}

TEST(OpponentDetectorTest, MovingOpponentVelocity)
{
  const CircleTrack t = makeCircle(20.0, 120, 1.5);
  ObsConfig cfg;
  TrackObservationBuilder builder(t.xs, t.ys, t.wl, t.wr, cfg);
  DetectorConfig dcfg;
  dcfg.vel_alpha = 1.0;  // no smoothing -> exact finite difference
  dcfg.max_range_m = 0.0;  // synthetic blob sits 20 m out (radius-20 circle)
  OpponentDetector det(builder, dcfg);

  // Opponent drifts +y at 0.5 m/s (dy = 0.05 per dt = 0.1), staying near centerline.
  DetectionResult res;
  for (int k = 0; k < 4; ++k) {
    res = det.update(blobBeams(20.0, 0.05 * k, 5, 0.05), 0.0, 0.0, 0.1 * k);
  }
  EXPECT_TRUE(res.present);
  EXPECT_NEAR(res.vy, 0.5, 1e-3);
  EXPECT_NEAR(res.vx, 0.0, 1e-3);
}

TEST(OpponentDetectorTest, WallNeverConfirms)
{
  const CircleTrack t = makeCircle(20.0, 120, 1.5);
  ObsConfig cfg;
  TrackObservationBuilder builder(t.xs, t.ys, t.wl, t.wr, cfg);
  DetectorConfig dcfg;
  OpponentDetector det(builder, dcfg);

  DetectionResult res;
  for (int k = 0; k < 5; ++k) {
    res = det.update(blobBeams(21.4, 0.0, 5, 0.05), 0.0, 0.0, 0.1 * k);
  }
  EXPECT_FALSE(res.present);
}

TEST(OpponentDetectorTest, CloseRangePhantomRejected)
{
  const CircleTrack t = makeCircle(20.0, 120, 1.5);
  ObsConfig cfg;
  TrackObservationBuilder builder(t.xs, t.ys, t.wl, t.wr, cfg);
  DetectorConfig dcfg;
  OpponentDetector det(builder, dcfg);

  // Bumper-range phantom ~0.3 m ahead of ego at the origin.
  const auto phantom = carBlobScan(0.3, 0.0, 5, 0.04);
  const auto clusters = det.cluster(phantom);
  ASSERT_EQ(clusters.size(), 1u);
  EXPECT_LT(det.clusterNearEdgeDist(phantom, clusters[0], 0.0, 0.0), 0.35);
  EXPECT_FALSE(det.standsOut(phantom, clusters[0], 0.0, 0.0));

  DetectionResult res;
  for (int k = 0; k < 5; ++k) {
    res = det.update(phantom, 0.0, 0.0, 0.1 * k);
  }
  EXPECT_FALSE(res.present);
}

TEST(OpponentDetectorTest, StaticOpponentAt7mConfirmed)
{
  const CircleTrack t = makeCircle(20.0, 120, 1.5);
  ObsConfig cfg;
  TrackObservationBuilder builder(t.xs, t.ys, t.wl, t.wr, cfg);
  DetectorConfig dcfg;
  OpponentDetector det(builder, dcfg);

  // Ego at (13, 0), opponent car-sized blob on centerline ~7 m ahead at (20, 0).
  const double ego_x = 13.0;
  const double ego_y = 0.0;
  const auto scan = carBlobScan(20.0, 0.0, 8, 0.04);

  DetectionResult res;
  for (int k = 0; k < 3; ++k) {
    res = det.update(scan, ego_x, ego_y, 0.1 * k);
  }
  EXPECT_TRUE(res.present);
  EXPECT_NEAR(res.pos_x, 20.0, 0.15);
  EXPECT_NEAR(res.pos_y, 0.0, 0.15);
  EXPECT_NEAR(res.vx, 0.0, 1e-6);
  EXPECT_NEAR(res.vy, 0.0, 1e-6);
}

TEST(OpponentDetectorTest, BeamAndAngleGatesDisable)
{
  const CircleTrack t = makeCircle(20.0, 120, 1.5);
  ObsConfig cfg;
  TrackObservationBuilder builder(t.xs, t.ys, t.wl, t.wr, cfg);
  DetectorConfig dcfg;
  dcfg.min_cluster_beams = 0;
  dcfg.min_ego_dist_m = 0.0;
  dcfg.min_visible_angle_deg = 0.0;
  OpponentDetector det(builder, dcfg);

  const auto fragment = blobBeams(20.0, 0.0, 2, 0.05);
  const auto clusters = det.cluster(fragment);
  ASSERT_EQ(clusters.size(), 1u);
  EXPECT_TRUE(det.passesBeamGates(clusters[0], 0.0));
}

TEST(OpponentDetectorTest, ReplayGymScanFixture)
{
  // Schema (written by test/record_gym_scan_fixture.py):
  // { "track_csv": "optional/path.csv",
  //   "frames": [ { "ranges": [...], "angle_min", "angle_increment",
  //                 "ego_x", "ego_y", "ego_yaw", "opp_x", "opp_y" }, ... ] }
  const std::string path = gymScanFixturePath();
  std::vector<GymScanFrame> frames;
  std::string track_csv;
  if (!loadGymScanFixture(path, frames, &track_csv)) {
    GTEST_SKIP() << "gym scan fixture not found or unreadable: " << path;
  }
  ASSERT_FALSE(frames.empty());

#ifdef IV2026_TRACK_CSV_PATH
  if (track_csv.empty()) {
    track_csv = IV2026_TRACK_CSV_PATH;
  }
#endif
  ObsConfig cfg;
  std::unique_ptr<TrackObservationBuilder> builder;
  if (!track_csv.empty()) {
    try {
      const TrackData track = loadTrackCsv(track_csv);
      builder = std::make_unique<TrackObservationBuilder>(
        track.x, track.y, track.w_left, track.w_right, cfg);
    } catch (const std::exception & e) {
      GTEST_SKIP() << "cannot load track_csv '" << track_csv << "': " << e.what();
    }
  } else {
    const CircleTrack t = makeCircle(20.0, 120, 1.5);
    builder = std::make_unique<TrackObservationBuilder>(
      t.xs, t.ys, t.wl, t.wr, cfg);
  }

  DetectorConfig dcfg;
  OpponentDetector det(*builder, dcfg);

  int gt_visible = 0;
  int confirmed = 0;
  double sum_err = 0.0;
  for (size_t f = 0; f < frames.size(); ++f) {
    const GymScanFrame & frame = frames[f];
    ASSERT_FALSE(frame.ranges.empty());
    const auto beams = rangesToMapBeams(
      frame.ranges, frame.angle_min, frame.angle_increment,
      frame.ego_x, frame.ego_y, frame.ego_yaw);
    const DetectionResult res = det.update(
      beams, frame.ego_x, frame.ego_y, 0.1 * static_cast<double>(f),
      frame.angle_increment);

    const bool has_gt =
      std::isfinite(frame.opp_x) && std::isfinite(frame.opp_y) &&
      (std::abs(frame.opp_x) > 1e-6 || std::abs(frame.opp_y) > 1e-6);
    if (!has_gt) {
      continue;
    }
    ++gt_visible;
    if (res.present) {
      ++confirmed;
      const double dx = res.pos_x - frame.opp_x;
      const double dy = res.pos_y - frame.opp_y;
      sum_err += std::sqrt(dx * dx + dy * dy);
    }
  }
  if (gt_visible == 0) {
    GTEST_SKIP() << "fixture has no GT opponent frames";
  }
  const double recall = static_cast<double>(confirmed) / static_cast<double>(gt_visible);
  EXPECT_GT(recall, 0.5) << "recall on recorded gym fixture";
  if (confirmed > 0) {
    EXPECT_LT(sum_err / confirmed, 1.5) << "mean position error (m)";
  }
}

TEST(RlObsCore, LagFilter)
{
  EXPECT_NEAR(f1tenth_rl_vehicle::lagAlpha(0.1, 0.1), 0.5, 1e-9);
  EXPECT_NEAR(f1tenth_rl_vehicle::stepFirstOrderLag(0.0, 1.0, 0.5), 0.5, 1e-9);
  EXPECT_NEAR(f1tenth_rl_vehicle::stepFirstOrderLag(0.5, 1.0, 0.5), 0.75, 1e-9);
}

TEST(RlObsCore, MapActionToForce)
{
  auto [long_cmd, steer] =
    f1tenth_rl_vehicle::mapActionToForce(0.5, -0.5, 0.44, 1.0);
  EXPECT_NEAR(long_cmd, 0.5, 1e-9);
  EXPECT_NEAR(steer, -0.22, 1e-9);

  auto [brake_cmd, steer0] =
    f1tenth_rl_vehicle::mapActionToForce(-0.8, 0.0, 0.44, 1.0);
  EXPECT_NEAR(brake_cmd, -0.8, 1e-9);
  EXPECT_NEAR(steer0, 0.0, 1e-9);

  auto [clipped, steer_clip] =
    f1tenth_rl_vehicle::mapActionToForce(5.0, -5.0, 0.44, 1.0);
  EXPECT_NEAR(clipped, 1.0, 1e-9);
  EXPECT_NEAR(steer_clip, -0.44, 1e-9);
}
