vesc_actuator:
  ros__parameters:
    i_drive_max_a: 10.0
    i_brake_max_a: 10.0
    i_brake_safe_a: 5.0
    watchdog_timeout_s: 0.15
    publish_rate_hz: 50.0
    i_slew_a_per_s: 200.0
    publish_servo: true
    ackermann_topic: /ackermann_cmd
    steering_angle_to_servo_gain: -1.2135
    steering_angle_to_servo_offset: 0.4495
